### PR TITLE
Upgrade to new Silex API

### PR DESCRIPTION
**Pull request by kbariotis**
- Implement new Silex's ServiceProviderInterface
- Remove Pimple
- Update Doctrine

### CODE REVIEW

**Comment by dominikzogg** [comment]
@kbariotis why all this changes? this provider should work with silex 2 as it is.

**Comment by dominikzogg** [comment]
@kbariotis and if not we should fix it, but using this interface is not an option for me, cause this provider should work with plain pimple too

**Comment by kbariotis** [comment]
Well with Silex won't work, cause Silex's `register()` expects it's own ServiceProviderInterface so it will throw an error when registering your Provider.

But you're right, i shouldn't PR like that. How will you continue?

**Comment by kbariotis** [comment]
hmmm @dominikzogg now i got what you are saying. 
So are you only supporting Silex 2?

**Comment by dominikzogg** [comment]
With the master branch, use v1 for silex 1.2
Am 21.01.2015 19:11 schrieb "Kostas Bariotis" notifications@github.com:

**Comment by dominikzogg** [comment]
Use this: https://github.com/saxulum/saxulum-doctrine-mongodb-provider/releases/tag/1.0.4

**Comment by kbariotis** [comment]
Great. So i'am closing this PR. Sorry for the inconvenience.

**Pull request closed without merging**
